version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./data:/var/lib/mysql
     restart: always
     command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
      - "3306:3306"  
     networks:
      - app-network

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8090:80"
     restart: always
     environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
     networks: 
      - app-network

   jenkins:
     image: jenkins:latest
     restart: always
     command: [apt-get update && apt-get upgrade -y]
     ports:
       - "8080:8080"
       - "50000:50000"
     environment: 
      JENKINS_SLAVE_AGENT_PORT: 50001
      JENKINS_ROOT_PASSWORD: jenkins
     networks: 
       - app-network
   alpine:
     image: alpine
     user: nobody:nobody
     networks: 
       - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge