version: '2'

services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
      - "3306:3306"  
     networks:
      - app-network
     labels: 
      - jenkins-slaves 

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8090:80"
     restart: always
     environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
     networks: 
      - app-network
     labels: 
      - jenkins-slaves   

   jenkins:
     image: 'bitnami/jenkins:2'
     volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/git/jenkins-persistence:/bitnami
     ports:
      - '8800:8080'
      - '8443:8443'
      - '50000:50000'
     networks: 
      - app-network
   alpine:
     image: alpine
     user: nobody:nobody
     networks: 
       - app-network
     labels: 
       - jenkins-slaves
#Docker Networks
networks:
  app-network:
    driver: bridge

## TEST